/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        for(int i = 2; i<=Math.sqrt(n);i++){
            if(n%i==0){
                return false;
            }
        }
        return (n>=2);
    }
    public long firstPrimeNumberIn(String n) {
        for(int i = 0; i<=n.length();i++){
            String sub = n.substring(i,i+10);
            long bleh = Long.parseLong(sub);
            if(isPrime(bleh)){
                return bleh;
            }
        }
        return -1;
    }
}
